name: Article Scraper Workflow

on:
  schedule:
    # Run every day at 3 a.m.
    - cron: '0 3 * * *'
  workflow_dispatch:
    # Manually launch workflow from GitHub interface

jobs:
  scrape_articles:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests
      
      - name: Create config directory
        run: mkdir -p config
      
      - name: Create Firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" > config/firebase.json
      
      - name: Set API keys
        run: |
          sed -i "s/your_ieee_key/${{ secrets.IEEE_API_KEY }}/g" scraper.py
          sed -i "s/your_serp_key/${{ secrets.SERP_API_KEY }}/g" scraper.py
      
      - name: Run scraper
        run: python scraper.py
      
      - name: Upload results as artifact (if Firebase fails)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: scraped-articles
          path: articles_scraped.json
          if-no-files-found: ignore